volumes:
  park-it-data:
    external: true
  # pgadmin:
  #   external: true
services:
  postgres:
    build:
      context: ./relational-data
      dockerfile: ./Dockerfile.dev
    volumes:
      - park-it-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=accounts,parking
      - POSTGRES_PASSWORD=test-databases
    ports:
      - 15432:5432
  parking:
    build:
      context: parking
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./parking:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://parkit:password@db/parking
      WAIT_HOSTS: db:5432

  accounts:
    build:
      context: accounts
      dockerfile: Dockerfile.dev
    ports:
      - 8001:8000
    volumes:
      - ./accounts:/app
    environment:
      DATABASE_URL: postgresql://accounts:password@db/accounts
      WAIT_HOSTS: postgres:5432

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
